<?php $this->headTitle('Home'); ?>

<script>
  logInWithFacebook = function() {
    FB.login(function(response) {
      if (response.authResponse) {
        window.location = 'app';
      }
    }, {scope: 'email,user_managed_groups'});
    return false;
  };
  window.fbAsyncInit = function() {
    FB.init({
      appId: '198081521001550',
      cookie: true, // This is important, it's not enabled by default
      version: 'v3.0',
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Women Who Code Manila</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/zend-expressive-skeleton" target="_blank">zend-expressive skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        <?php
        $guestCount = 130;
        $guests = json_decode(file_get_contents('https://randomuser.me/api/?results='.$guestCount.'&nat=us&gender=female'), true);
        echo implode(' ', array_map(function($guest) {
            return sprintf('<img class="welcome-pic" src="%s">', $guest['picture']['medium']);
        }, $guests['results'])); ?>
    </p>
</div>

<div class="text-center">
  <a class="btn btn-primary" href="#" onClick="logInWithFacebook()">Join Women Who Code Manila</a>
</div>
