<?php $this->headTitle('Home'); ?>

<script>
  logInWithFacebook = function() {
    FB.login(function(response) {
      if (response.authResponse) {
        window.location = 'app';
      }
    }, {scope: 'email,user_managed_groups'});
    return false;
  };
  window.fbAsyncInit = function() {
    FB.init({
      appId: '198081521001550',
      cookie: true, // This is important, it's not enabled by default
      version: 'v3.0',
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="container">
  <div class="row">
    <div class="col-8">
    <p class="photo-collage">
        <?php
        $guestCount = 48;
        $guests = json_decode(file_get_contents('https://randomuser.me/api/?results='.$guestCount.'&nat=us&gender=female'), true);
        echo implode(' ', array_map(function($guest) {
            return sprintf('<img class="welcome-pic" src="%s">', $guest['picture']['medium']);
        }, $guests['results'])); ?>
    </p>
    </div>
    <div class="col">
      <h3 class="headline">Women Who Code is a global non-profit organization inspiring hundred of thousands of women all over the world to excel in their tech careers.</h3>
      <h3 class="call-to-action">Be part of our awesome community!</h3>
      <a class="btn btn-primary" href="#" onClick="logInWithFacebook()">Join Women Who Code Manila</a>
    </div>
  </div>
</div>
