<?php $this->headTitle('Home'); ?>

<h1 class="display-4 mb-4">Members</h1>

<div class="members">

<div class="m-1 member" onclick="window.location = 'https://7fd43a87.ngrok.io/members/aHR0cHM6Ly9pLmltZ3VyLmNvbS8zTGZLS25qLmpwZ35NaWNoaWU=';">
  <img class="member-pic-small" src="https://i.imgur.com/3LfKKnj.jpg">
  <div class="text-center">Michie</div>
</div>

<?php foreach ($this->members['results'] as $member) { ?>

<div class="m-1 member" onclick="window.location = '/members/' + '<?php echo base64_encode($member['picture']['large'] . '~' . ucwords($member['name']['first'])); ?>'">
  <img src="<?php echo $member['picture']['large']; ?>">
  <div class="text-center"><?php echo ucwords($member['name']['first']); ?></div>
</div>

<?php } ?>
</div>
