<?php $this->headTitle('Home'); ?>

<h1 class="display-4 mb-4">Join <span class="zf-green">Women Who Code Manila</span> today</h1>

<form method="post">
    <div class="form-group">
      <input class="form-control" type="text" name="name" placeholder="Name" value="<?php echo $name; ?>" required>
    </div>
    <div class="form-group">
      <input class="form-control" type="email" name="email" placeholder="Email" value="<?php echo $email; ?>" required>
    </div>
    <div class="form-group">
      <input class="form-control" type="text" name="phoneNumber" placeholder="Phone number" required>
    </div>
    <div class="form-group">
      <input class="form-control" type="text" name="position" placeholder="Position in the company" required>
    </div>
    <div class="form-group">
      <input class="form-control" type="number" name="experience" placeholder="Years of experience" required>
    </div>
    <div class="form-group">
      <textarea class="form-control" placeholder="Why did you join this community?"></textarea>
    </div>
    <div class="form-group form-check">
      <input type="checkbox" class="form-check-input" id="shareProfile">
      <label class="form-check-label" for="shareProfile">Share Facebook profile to other members?</label>
    </div>
    <button type="submit" class="btn btn-primary">Signup</button>
</form>
